= Android Application for Passel.

Some source files in this repository are licensed under different 
licenses and are copyright their respective authors. Information
about these copyrights is available at the top of those specific
files. Unless otherwise explicitly stated, all files in this
repository are licensed as follows.

== License

Copyright (C) 2015 Aneesh Agrawal, Lisandro Jimenez, Carlos Henriquez

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

